server:
  port: 9090
  
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: clientId
      client-secret: secret
      #access-token-uri: http://localhost:8501/auth/oauth/token
      access-token-uri: https://notewitch-auth-server.herokuapp.com/auth/oauth/token
      #user-authorization-uri: http://localhost:8501/auth/oauth/authorize
      user-authorization-uri: https://notewitch-auth-server.herokuapp.com/auth/oauth/authorize
    resource:
      user-info-uri: https://notewitch-auth-server.herokuapp.com/auth/getCurrentUser
      
spring:
  http:
    multipart:
      max-file-size: 5000KB